### ISSUE TITLE
Deprecated Dependencies

### ISSUE THREAD

**Issue by shivpratik** [getbrevo/brevo-node#2]
querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
superagent@3.7.0: Please upgrade to v7.0.2+ of superagent.

Kindly please update the libraries.

**Comment by shubhamUpadhyayInBlue** [comment]
Hi @shivpratik 
It will be fixed soon.

**Comment by shubhamUpadhyayInBlue** [comment]
A new version 1.0.1 is released for the same: https://www.npmjs.com/package/@getbrevo/brevo?activeTab=versions

**Comment by shivpratik** [comment]
Hi @shubhamUpadhyayInBlue

querystring@0.2.1 has not been updated. My application throws warning "The querystring API is considered Legacy. new code should use the URLSearchParams API instead."

Can you kindly do the needful.
